### ISSUE TITLE
Price of the phone not showing properly

### ISSUE THREAD

**Issue by ParvamShah1** [NiranjanKumar001/iPhone16Pro#27]
The price of the iPhone 16 Pro isn't displaying properly on your website clone.
The buy button is also not same as on the original website.
clone website -->
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/7c8aa470-a3ff-4df3-9bcb-e62c2e84ac90">
original website -->
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/0fa49de3-c3e3-4bb2-a4cb-c3ffbab63b53">

please assign me this issue , i would like to work on this .

**Comment by NiranjanKumar001** [comment]
@ParvamShah1 this is because the site not responsive so you gonna work on the buy button ,make sure properly design and it should not break other structures also the positioning it has now must be properly managed for different devices for proper responsiveness.

**Comment by ParvamShah1** [comment]
completed
