### ISSUE TITLE
Addition of CONTRIBUTING.md

### ISSUE THREAD

**Issue by AnuranjanJain** [NiranjanKumar001/iPhone16Pro#35]
I would like to request to be assigned the issue for adding a Contributing.md file to this Project Under Hacktoberfest. This file will provide clear guidelines for potential contributors, enhancing our community's onboarding experience and encouraging more participation.

**Comment by NiranjanKumar001** [comment]
@AnuranjanJain Great !! make sure to star the repo>create fork
